apiVersion: v2
name: backend
description: BACKEEEEEEEEEEEEEEEEEEEEND
type: application
version: 0.1.5
appVersion: "0.0.1"

dependencies:
  - name: rabbitmq
    version: 15.5.3
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: valkey
    version: 3.0.2
    repository: oci://registry-1.docker.io/bitnamicharts
