# Kubernetes manifest for setting up THE bank service
# Copyright (C) 2025  Arsen Arsenović <aarsenovic8422rn@raf.rs>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: '{{ .Release.Name }}-bank-service'
  name: '{{ .Release.Name }}-bank-service'
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '{{ .Release.Name }}-bank-service'
  template:
    metadata:
      labels:
        app: '{{ .Release.Name }}-bank-service'
    spec:
      volumes:
        - name: interbank-config
          secret:
            secretName: '{{ .Release.Name }}-interbank-config'
      containers:
      - image: harbor.k8s.elab.rs/banka-4/bank-service:{{ .Values.imageTag }}
        imagePullPolicy: Always
        name: bank-service
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-pguser-bank-service
                key: jdbc-uri
          - name: SPRING_RABBITMQ_USERNAME
            value: 'user'
          - name: SPRING_RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rabbitmq
                key: rabbitmq-password
          - name: SPRING_RABBITMQ_HOST
            value: {{ .Release.Name }}-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-jwt-secret
                key: key
          - name: JWT_EXPIRATION
            value: '180000'
          - name: ALPHAVANTAGE_APIKEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-alphavantage
                key: apikey
          - name: SERVICES_EXCHANGE
            value: http://{{ .Release.Name }}-exchange-office.{{ .Release.Namespace }}.svc.cluster.local:8000/
          - name: RAFEISEN_CACHE_VALKEY_HOST
            value: {{ .Release.Name }}-valkey-primary.{{ .Release.Namespace }}.svc.cluster.local
          - name: RAFEISEN_CACHE_VALKEY_PORT
            value: '6379'
        volumeMounts:
          - mountPath: /work/application.yml
            name: interbank-config
            subPath: interbank
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-bank-service
  name: {{ .Release.Name }}-bank-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-bank-service
  type: ClusterIP
